name: HACS validation

on:
  push:
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hacs:
    name: HACS
    runs-on: ubuntu-latest
    steps:
      - name: Validate HACS publishing requirements
        uses: hacs/action@main
        with:
          category: integration
          comment: false

  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Validate Home Assistant integration
        uses: home-assistant/actions/hassfest@master
