name: HACS validation

on:
  workflow_call:
  push:
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hacs:
    name: HACS
    runs-on: [self-hosted, Linux, X64, espcontrol-immich]
    steps:
      - name: Validate HACS publishing requirements
        uses: hacs/action@main
        with:
          category: integration
          comment: false
